In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Numpy

In [ ]:
# 1D array
nparray = np.array([1,2,3,4,5])
print(nparray, type(nparray))

# 2D array
nparray2 = np.array([[1,2,3],[4,5,6]]) 
nparray2

[1 2 3 4 5] <class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Garbage array:
np.empty(5)

# Array of ones
np.ones(5)

# Array of zeros
np.zeros(5)

# Identity matrix
np.eye(5)

# (start, stop, step)
np.arange(0, 100, 5)

# Updating array values in defined range
my_arr = np.random.random(7)
my_arr[0:2] = 5
my_arr * 10

array([50.        , 50.        ,  9.01041561,  0.49926804,  7.06399651,
        7.51047974,  4.73298076])

In [ ]:
# Getting one column of a matrix
matrix = np.array([[1,2,3],[4,5,6], [7, 8, 9]])
for i in range(3):
  #print(matrix[:,i:i+1])
  print("------")


# Transposicion de arreglo
arr = np.ones(20).reshape(10, 2)
transpose = arr.transpose()
print("Reshaped\n", arr)
print("Transposed\n",transpose)

------
------
------
Reshaped
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Transposed
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# Array operations for every element
arr = np.arange(0, 11, 1)
arr1 = np.arange(0, 11, 1) * 2

np.exp(arr)
np.square(arr)
np.sqrt(arr)
np.cbrt(arr)

np.add(arr, arr1)
np.subtract(arr1, arr)

# Broadcasting
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(a.shape, b.shape)

print(a.reshape(1,2,3))
print(b.reshape(3,1,3))

#a + b # Error 

a.reshape(1,2,3) + b.reshape(3,1,3)


(2, 3) (3, 3)
[[[1 2 3]
  [4 5 6]]]
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


array([[[ 2,  4,  6],
        [ 5,  7,  9]],

       [[ 5,  7,  9],
        [ 8, 10, 12]],

       [[ 8, 10, 12],
        [11, 13, 15]]])

In [ ]:
# Pandas

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
# Shape(rows, columns)
df.shape
df.columns

# Get the head rows from a specific column
df['sepal_length'].head()

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal_length, dtype: float64

In [ ]:
new_df = pd.DataFrame(df, columns=['petal_length', 'petal_width'])
new_df['amount'] = np.random.random(new_df.shape[0]) * 100
new_df

petal_length  petal_width     amount
0             1.4          0.2  65.283812
1             1.4          0.2  40.268124
2             1.3          0.2  29.893999
3             1.5          0.2  80.288255
4             1.4          0.2  49.153809
..            ...          ...        ...
145           5.2          2.3  93.839035
146           5.0          1.9  31.765162
147           5.2          2.0  34.263709
148           5.4          2.3  20.058005
149           5.1          1.8  25.161138

[150 rows x 3 columns]

In [ ]:
'''
Path Planning
Search-Based Algorithm: A*
Sampling-Based Algorithm: RRT, RRT* - (used for multi-dimension and large amount of nodes)

RRT - Rapidly Exploring Random Trees

It is not necesary to use a fully connected graph structure, we just need a tree, in a tree each node has a single parent.
We will remove the edge for the longer path.


Common Hyper Parameters:
- fit_intercept: whether to calculate the intercept of the model, not required if data is centered
- normalize: X will be normalized by substracting mean & dividing by standad deviation

Common Attributes:
- coef: weights for each independent variable
- intercept: bias of independent term of linear models

Common functions:
- fit: trains the model. Takes X and y
- predict: once the model is trained, for given X using the predict function Y can be predicted

Lasso: 
- linear model that predicts spase coefficients
- reduces the regressors predicting target

Elastic Net
- Elsatic-net is useful when there are multiple features which are correlated with one another, Lasso is likely to pick one of these at random, while elastic-net is likely to pick both

Logistic Regression
- Linear model of classification, assures linear relationship between features and target
- Returns class probabilities
- Hyperparameter C- regularization coeficient

'''

In [ ]:
# Naive Bayes
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')

# Bayes probability calculation
# P(species | sl.sp.pl.pw)
X = data.iloc[:,:4].values
y = data['species'].values

print(data.head())

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_predicted = classifier.predict(X_test)

cm = confusion_matrix(y_test, y_predicted)
print(cm)

manual_predict = classifier.predict(np.array([0.1, 0.5, 0.3, 0.4]).reshape(1, -1))
print(manual_predict)

print("Accuracy score: ", accuracy_score(y_test, y_predicted))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
[[11  0  0]
 [ 0  9  0]
 [ 0  0 10]]
['virginica']
Accuracy score:  1.0
